#!/bin/bash

main() {
    # Read data in
    local -r input=$(<input)

    local -i sum=0

    # For each character
    for ((index=0; index < ${#input}; ++index)); do
        # If the character is part of a number
        if [[ ${input:$index:1} =~ [0-9-] ]]; then
            local -i startIndex=$index
            local -i length=1

            # Find length of number
            for ((index2=index + 1; index2 < ${#input}; ++index2)); do
                if [[ ${input:$index2:1} =~ [0-9-] ]]; then
                    ((++length))
                else
                    break
                fi
            done

            # Add number to sum
            ((sum += ${input:$index:$length}))

            # Skip characters to stop us re-reading half a number
            ((index += length - 1))
        fi
    done

    echo "Sum of all numbers is $sum"
}

main "$@"
