#!/bin/bash

main() {
    local -i NUM_LITRES=150

    # Read container sizes from file
    local -a containers=( $(cat input | tr '\n' ' ') )

    local -i numContainers=${#containers[@]}

    # Calculate the number of iterations we need to do
    local -i maxIterations=$((2 ** numContainers))

    local -i combinations=0

    # Loop through each iteration
    for ((index=0; index<maxIterations; ++index)); do
        local -i capacity=0

        # Calculate how many litres this iteration can hold
        for ((index2=0; index2<numContainers; ++index2)); do
            ((capacity += ${containers[index2]} * ((index & (2 ** index2)) != 0)))

            # If we have exceeded the capacity then break early
            if test $capacity -gt $NUM_LITRES; then
                break
            fi
        done

        if test $capacity -eq $NUM_LITRES; then
            ((++combinations))

            echo "Combination found : $index"
        fi
    done

    echo "The number of combinations is $combinations"
}

main "$@"
